import { useEffect, useState } from 'react'
export const A = '/assets/images/'
export const nav = [['/','Home'],['/about','About BOAC'],['/programmes','Programmes'],['/youth','Youth Development'],['/media','Media'],['/gallery','Gallery'],['/get-involved','Get Involved'],['/contact','Contact']]

export function Link({to,children,className='',onClick}) {
  const go=(event)=>{ if(to.startsWith('http')||to.startsWith('mailto:')||to.startsWith('tel:')||to.startsWith('#')) return; event.preventDefault(); history.pushState({},'',to); dispatchEvent(new PopStateEvent('popstate')); scrollTo(0,0); onClick?.() }
  return <a href={to} className={className} onClick={go}>{children}</a>
}
export function Navbar({path}) {
  const [open,setOpen]=useState(false),[scrolled,setScrolled]=useState(false)
  useEffect(()=>{const fn=()=>setScrolled(scrollY>20);fn();addEventListener('scroll',fn,{passive:true});return()=>removeEventListener('scroll',fn)},[])
  return <><nav className={`navbar ${scrolled?'scrolled':''}`}><div className="container"><Link to="/" className="nav-logo"><img src={`${A}boac-logo.png`} alt="BOAC logo"/><span className="nav-logo-name">BOAC</span></Link><div className="nav-links">{nav.map(([to,label])=><Link key={to} to={to} className={path===to?'active':''}>{label}</Link>)}</div><div className="nav-right"><Link to="/donate" className="btn btn-amber">Donate</Link><div className="nav-avatar" aria-hidden="true">👤</div></div><button className={`hamburger ${open?'open':''}`} aria-label="Toggle menu" aria-expanded={open} onClick={()=>setOpen(v=>!v)}><span/><span/><span/></button></div></nav><div className={`mobile-nav ${open?'open':''}`}>{nav.map(([to,label])=><Link key={to} to={to} onClick={()=>setOpen(false)}>{label}</Link>)}<Link to="/donate" className="btn btn-amber" onClick={()=>setOpen(false)}>Donate</Link></div></>
}
export function Footer(){return <footer className="footer"><div className="container"><div className="footer-grid"><div><img src={`${A}boac-logo.png`} alt="BOAC logo" className="footer-brand-img"/><p className="footer-tagline">Batšofe Tiang Maatla — The elderly guide our strength</p><div className="footer-address">📍 Bokwidi Village, Waterberg District, Limpopo</div></div><div><div className="footer-col-title">Quick Links</div><div className="footer-links"><Link to="/volunteer">Volunteer</Link><Link to="/gallery">Gallery</Link><Link to="/about">About BOAC</Link><Link to="/contact">Contact us</Link></div></div><div><div className="footer-col-title">Connect</div><div className="footer-social"><a href="#facebook" className="social-btn" aria-label="Facebook">f</a><a href="#community" className="social-btn" aria-label="Community">👥</a><a href="#events" className="social-btn" aria-label="Events">📅</a></div></div></div><div className="footer-bottom"><p>© 2026 Bokwidi Old Age Centre. All rights reserved.</p><p>🌍 Registered Non-Profit Organisation</p></div></div></footer>}
export function PageHero({image,eyebrow,title,text,children}){return <section className="page-hero react-page-hero"><img src={`${A}${image}`} alt="" className="page-hero-img"/><div className="page-hero-overlay"/><div className="container"><div className="page-hero-content"><span className="label hero-label">{eyebrow}</span><h1>{title}</h1>{text&&<p>{text}</p>}{children}</div></div></section>}
export function SectionTitle({eyebrow,title,text}){return <div className="section-header fade-up visible">{eyebrow&&<p className="eyebrow">{eyebrow}</p>}<h2>{title}</h2>{text&&<p>{text}</p>}</div>}
export function CTA({title='Be Part of Their Story',text='Your support helps us continue providing essential care, companionship and dignity to the elders of Bokwidi.'}){return <section className="cta-section section"><div className="container"><h2>{title}</h2><p>{text}</p><div className="cta-actions"><Link to="/donate" className="btn btn-amber btn-lg">Donate Today</Link><Link to="/volunteer" className="btn btn-outline-white btn-lg">Volunteer</Link></div></div></section>}
export function Card({icon,title,children,link,linkText='Learn More'}){return <article className="prog-card fade-up visible"><div className="prog-icon">{icon}</div><h3>{title}</h3><p>{children}</p>{link&&<Link to={link} className="prog-link">{linkText} →</Link>}</article>}
export function Field({label,type='text',select,options=[],textarea}){const id=label.toLowerCase().replaceAll(' ','-');return <div className="form-group"><label htmlFor={id}>{label}</label>{select?<select id={id} className="form-select" required><option value="">Please select</option>{options.map(o=><option key={o}>{o}</option>)}</select>:textarea?<textarea id={id} className="form-textarea" placeholder="Write your message here…" required/>:<input id={id} className="form-input" type={type} required/>}</div>}
export function FormStatus({status}){return status?<div className="form-success" role="status">✓ {status}</div>:null}
